remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-github-metadata

logo: img/profile.jpeg
show_downloads: false
title: "Samuel Buhan"
description: Embedded Software Engineer | C / Python / IoT Systems
author: Samuel Buhan
lang: en

github:
  username: SamuelBuhan
  repository: SamuelBuhan.github.io # your repo name
  user_page: true 


# Social links
github_username: SamuelBuhan
linkedin_username: samuel-buhan

# Build settings
markdown: kramdown
permalink: pretty
google_analytics: G-W1M4LDZ2X1
