remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

logo: img/profile.jpeg
show_downloads: true
title: "Discover me - Samuel Buhan"
description: Embedded Software Engineer | C / Python / IoT Systems
author: Samuel Buhan
lang: en

nav:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects/"
  - title: "Education"
    url: "/education/"
  - title: "Work Experiences"
    url: "/work/"
  - title: "About"
    url: "/about/"

# Social links
github_username: SamuelBuhan
linkedin_username: samuel-buhan

# Build settings
markdown: kramdown
permalink: pretty
google_analytics: G-W1M4LDZ2X1
